name: UnitLib
version: "5.0.0"
license: "GPL-2.0-or-later"
date: 2025-06-12
description: |
    Library of normalized unit groups of modular group algebras

authors:
    - name: Olexandr Konovalov
      url: https://olexandr-konovalov.github.io/
    - name: Olena Yakimenko
    - name: Kamil Zabielski
      url: https://limakzi.me

maintainers:
    - name: Olexandr Konovalov
      url: https://olexandr-konovalov.github.io/
    - name: Kamil Zabielski
      url: https://limakzi.me

GAP: ">=4.11"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.6"
      url: "https://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "IO"
      version: "4.5"
      url: "https://gap-packages.github.io/io"
    - name: "LAGUNA"
      version: ">= 3.9.4"
      url: "https://gap-packages.github.io/laguna"

suggested-pkgs:
    - name: "SCSCP"
      version: ">=2.2"
      url: "https://gap-packages.github.io/scscp"

www: https://gap-packages.github.io/unitlib
readme: README.md
packageinfo: https://gap-packages.github.io/unitlib/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/unitlib/releases/download/v5.0.0/unitlib-5.0.0.tar.gz

abstract: |
    The <span class="pkgname">UnitLib</span> package extends the <span class="pkgname">LAGUNA</span> package and provides the library of normalized unit groups of modular group algebras of all finite p-groups of order up to 243 over the field of p elements.

status: accepted
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    group ring, modular group algebra, normalized unit group.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>KYZ25</span>]   <b class='BibAuthor'>Konovalov, O., Yakimenko, O. and Zabielski, K.</b>,
     <i class='BibTitle'>UnitLib, Library of normalized unit groups of modular group algebras,
             Version 5.0.0</i>
     (<span class='BibYear'>2025</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/unitlib">https://gap-packages.github.io/unitlib</a></span>.
    </p>
    

bibtex: |
    @misc{ UnitLib,
      author =           {Konovalov, O. and Yakimenko, O. and Zabielski, K.},
      title =            {{UnitLib},  {Library  of  normalized  unit  groups  of
                          modular group algebras}, {V}ersion 5.0.0},
      month =            {Jun},
      year =             {2025},
      note =             {GAP package},
      howpublished =     {\href         {https://gap-packages.github.io/unitlib}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{unitlib}}},
      keywords =         {group  ring;  modular  group  algebra; normalized unit
                          group},
      printedkey =       {KYZ25}
    }

